// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkSTQ6PwEYtKQuzMe_GJt6x2fESNGM04',
    appId: '1:725871129285:android:fbf78b68b07590f327f6ac',
    messagingSenderId: '725871129285',
    projectId: 'togetherremind',
    storageBucket: 'togetherremind.firebasestorage.app',
    databaseURL: 'https://togetherremind-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolavJ_1dNiEZ42dLd7OmANLCcKTvyPJg',
    appId: '1:725871129285:ios:9b09ef0e56448b1727f6ac',
    messagingSenderId: '725871129285',
    projectId: 'togetherremind',
    storageBucket: 'togetherremind.firebasestorage.app',
    databaseURL: 'https://togetherremind-default-rtdb.firebaseio.com',
    iosBundleId: 'com.togetherremind.togetherremind',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh97osauFB0ljuBr5MU5QfHX6Zx3XOZ80',
    appId: '1:725871129285:web:5c82d5e18390e80c27f6ac',
    messagingSenderId: '725871129285',
    projectId: 'togetherremind',
    authDomain: 'togetherremind.firebaseapp.com',
    databaseURL: 'https://togetherremind-default-rtdb.firebaseio.com',
    storageBucket: 'togetherremind.firebasestorage.app',
  );

}